# nginx/nginx.conf
events {
    worker_connections 1024;
}

http {
    upstream restaurante_blue {
        server app-prod-blue:3000;
    }

    upstream restaurante_green {
        server app-prod-green:3000;
    }

    # Logging format con métricas de tiempo de respuesta
    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time uct=$upstream_connect_time';

    access_log /var/log/nginx/access.log main;
    error_log  /var/log/nginx/error.log warn;

    # Gzip
    gzip on;
    gzip_types text/plain application/json;

    include /etc/nginx/conf.d/*.conf;
}
